package com.egov.secrecysystem.model;
// default package
// Generated Aug 18, 2014 4:45:24 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CpAnswerRecord generated by hbm2java
 */
public class CpAnswerRecord implements java.io.Serializable {

	private String id;
	private CpQuestion cpQuestion;
	private CpUser cpUser;
	private Date time;
	private String name;
	private String loginname;
	private Integer number;
	private String answer;
	private String useranswer;
	private Integer isright;
	private String remark;

	public CpAnswerRecord() {
	}

	public CpAnswerRecord(String id) {
		this.id = id;
	}

	public CpAnswerRecord(String id, CpQuestion cpQuestion, CpUser cpUser,
			Date time, String name, String loginname, Integer number,
			String answer, String useranswer, Integer isright, String remark) {
		super();
		this.id = id;
		this.cpQuestion = cpQuestion;
		this.cpUser = cpUser;
		this.time = time;
		this.name = name;
		this.loginname = loginname;
		this.number = number;
		this.answer = answer;
		this.useranswer = useranswer;
		this.isright = isright;
		this.remark = remark;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public Integer getNumber() {
		return number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CpQuestion getCpQuestion() {
		return this.cpQuestion;
	}

	public void setCpQuestion(CpQuestion cpQuestion) {
		this.cpQuestion = cpQuestion;
	}

	public CpUser getCpUser() {
		return this.cpUser;
	}

	public void setCpUser(CpUser cpUser) {
		this.cpUser = cpUser;
	}

	public String getUseranswer() {
		return this.useranswer;
	}

	public void setUseranswer(String useranswer) {
		this.useranswer = useranswer;
	}

	public Integer getIsright() {
		return this.isright;
	}

	public void setIsright(Integer isright) {
		this.isright = isright;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
