package com.egov.secrecysystem.model;
// default package
// Generated Aug 21, 2014 3:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CpMainmenu generated by hbm2java
 */
public class CpMainmenu implements java.io.Serializable {

	private String id;
	private CpRole cpRole;
	private CpMainmenu cpMainmenu;
	private String menuid;
	private String showname;
	private String onclickscript;
	private Integer sortindex;
	private Set<CpMainmenu> cpMainmenus = new HashSet<CpMainmenu>(0);

	public CpMainmenu() {
	}

	public CpMainmenu(String id, String menuid) {
		this.id = id;
		this.menuid = menuid;
	}

	public CpMainmenu(String id, CpRole cpRole, CpMainmenu cpMainmenu,
			String menuid, String showname, String onclickscript,
			Integer sortindex, Set<CpMainmenu> cpMainmenus) {
		this.id = id;
		this.cpRole = cpRole;
		this.cpMainmenu = cpMainmenu;
		this.menuid = menuid;
		this.showname = showname;
		this.onclickscript = onclickscript;
		this.sortindex = sortindex;
		this.cpMainmenus = cpMainmenus;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CpRole getCpRole() {
		return this.cpRole;
	}

	public void setCpRole(CpRole cpRole) {
		this.cpRole = cpRole;
	}

	public CpMainmenu getCpMainmenu() {
		return this.cpMainmenu;
	}

	public void setCpMainmenu(CpMainmenu cpMainmenu) {
		this.cpMainmenu = cpMainmenu;
	}

	public String getMenuid() {
		return this.menuid;
	}

	public void setMenuid(String menuid) {
		this.menuid = menuid;
	}

	public String getShowname() {
		return this.showname;
	}

	public void setShowname(String showname) {
		this.showname = showname;
	}

	public String getOnclickscript() {
		return this.onclickscript;
	}

	public void setOnclickscript(String onclickscript) {
		this.onclickscript = onclickscript;
	}

	public Integer getSortindex() {
		return this.sortindex;
	}

	public void setSortindex(Integer sortindex) {
		this.sortindex = sortindex;
	}

	public Set<CpMainmenu> getCpMainmenus() {
		return this.cpMainmenus;
	}

	public void setCpMainmenus(Set<CpMainmenu> cpMainmenus) {
		this.cpMainmenus = cpMainmenus;
	}

}
