package com.egov.secrecysystem.model;
// default package
// Generated Aug 18, 2014 4:45:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CpQuestion generated by hbm2java
 */
public class CpQuestion implements java.io.Serializable {

	private String id;
	private Integer number;
	private String question;
	private String rightanswer;
	private Integer scorevalue;
	private String remark;
	private Set<CpAnswerRecord> cpAnswerRecords = new HashSet<CpAnswerRecord>(0);

	public CpQuestion() {
	}

	public CpQuestion(String id) {
		this.id = id;
	}

	public CpQuestion(String id, Integer number, String question,
			String rightanswer, Integer scorevalue, String remark,
			Set<CpAnswerRecord> cpAnswerRecords) {
		this.id = id;
		this.number = number;
		this.question = question;
		this.rightanswer = rightanswer;
		this.scorevalue = scorevalue;
		this.remark = remark;
		this.cpAnswerRecords = cpAnswerRecords;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getRightanswer() {
		return this.rightanswer;
	}

	public void setRightanswer(String rightanswer) {
		this.rightanswer = rightanswer;
	}

	public Integer getScorevalue() {
		return this.scorevalue;
	}

	public void setScorevalue(Integer scorevalue) {
		this.scorevalue = scorevalue;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<CpAnswerRecord> getCpAnswerRecords() {
		return this.cpAnswerRecords;
	}

	public void setCpAnswerRecords(Set<CpAnswerRecord> cpAnswerRecords) {
		this.cpAnswerRecords = cpAnswerRecords;
	}

}
