package com.egov.secrecysystem.model;
// default package
// Generated Aug 21, 2014 3:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CpRole generated by hbm2java
 */
public class CpRole implements java.io.Serializable {

	private String id;
	private String name;
	private Integer rolenum;
	private String remark;
	private Set<CpUser> cpUsers = new HashSet<CpUser>(0);
	private Set<CpMainmenu> cpMainmenus = new HashSet<CpMainmenu>(0);

	public CpRole() {
	}

	public CpRole(String id) {
		this.id = id;
	}

	public CpRole(String id, String name,Integer rolenum, String remark, Set<CpUser> cpUsers,
			Set<CpMainmenu> cpMainmenus) {
		this.id = id;
		this.name = name;
		this.rolenum = rolenum;
		this.remark = remark;
		this.cpUsers = cpUsers;
		this.cpMainmenus = cpMainmenus;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<CpUser> getCpUsers() {
		return this.cpUsers;
	}

	public void setCpUsers(Set<CpUser> cpUsers) {
		this.cpUsers = cpUsers;
	}

	public Set<CpMainmenu> getCpMainmenus() {
		return this.cpMainmenus;
	}

	public void setCpMainmenus(Set<CpMainmenu> cpMainmenus) {
		this.cpMainmenus = cpMainmenus;
	}

	public Integer getRolenum() {
		return rolenum;
	}

	public void setRolenum(Integer rolenum) {
		this.rolenum = rolenum;
	}

}
