package com.egov.secrecysystem.model;
// Generated 2012-3-26 19:37:27 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

/**
 * ExMainmenu generated by hbm2java
 */
@DataTransferObject
public class SeMainmenu  implements java.io.Serializable {


     private String id;
     private SeRole seRole;
     private SeMainmenu SeMainmenu;
     private String menuid;
     private String showname;
     private String onclickscript;
     private Integer sortindex;
     private Set seMainmenus = new HashSet(0);

    public SeMainmenu() {
    }

	
    public SeMainmenu(String id, String menuid) {
        this.id = id;
        this.menuid = menuid;
    }
    public SeMainmenu(String id, SeRole seRole,SeMainmenu SeMainmenu , String menuid, String showname, String onclickscript, Integer sortindex, Set inMainmenus) {
       this.id = id;
       this.seRole = seRole;
       this.SeMainmenu = SeMainmenu;
       this.menuid = menuid;
       this.showname = showname;
       this.onclickscript = onclickscript;
       this.sortindex = sortindex;
       this.seMainmenus = inMainmenus;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public SeRole getSeRole() {
        return this.seRole;
    }
    
    public void setSeRole(SeRole seRole) {
        this.seRole = seRole;
    }
    public SeMainmenu getSeMainmenu() {
       return this.SeMainmenu;
   }
    
    public void setSeMainmenu(SeMainmenu SeMainmenu) {
        this.SeMainmenu = SeMainmenu;
    }
    public String getMenuid() {
        return this.menuid;
    }
    
    public void setMenuid(String menuid) {
        this.menuid = menuid;
    }
    public String getShowname() {
        return this.showname;
    }
    
    public void setShowname(String showname) {
        this.showname = showname;
    }
    public String getOnclickscript() {
        return this.onclickscript;
    }
    
    public void setOnclickscript(String onclickscript) {
        this.onclickscript = onclickscript;
    }
    public Integer getSortindex() {
        return this.sortindex;
    }
    
    public void setSortindex(Integer sortindex) {
        this.sortindex = sortindex;
    }
    public Set getSeMainmenus() {
        return this.seMainmenus;
    }
    
    public void setSeMainmenus(Set seMainmenus) {
        this.seMainmenus = seMainmenus;
    }




}


